### ISSUE TITLE
Strange - value.

### ISSUE THREAD

**Issue by Remski01** [electronicboy/mcmmo-placeholders#2]
Hello.

The placholder "%mcmmo_xp_remaining_Fishing%" seem to not work correctly, as it display a - value rather then... well.. The next level requirment value.

See the schreenshot for a more clear example.

https://postimg.cc/XBgsg8Lw/51065d10

Some more info:
mcMMO - 2.1.87 > Yes, i know. Outdated version(very outdated too), if you want to see if this still happen on the lastest version, please wait. Will test this also on the latest.
Paper - 1.14.4 (186)

**Comment by Remski01** [comment]
It also seem to happen to the "%mcmmo_xp_remaining_Taming%".

**Comment by electronicboy** [comment]
Issue was determined to be down to mcmmo and it's handling of configuration changes around experience
