### ISSUE TITLE
Placeholder for top Power Level

### ISSUE THREAD

**Issue by SrBedrock** [electronicboy/mcmmo-placeholders#3]
Create a placeholder that returns the power level rank.

Example: `mcmmo_rank_power_level` returns the player rank.

**Comment by mrfloris** [comment]
Being able to get 
```
1-bob
2-sara
3-notch
```
through placeholders would be nice.

**Comment by Kraxous** [comment]
Anything further on something like this? Appreciate it's a necro, but didn't want to open another issue with his one being open.

Something such as:
`%mcmmo_user_powerlevel_[1-10]%` - Which then has a top leaderboard for the top 10 users.

`%mcmmo_user_subskill_[1-10]%` - Would display a subskill (swords, unarmed, woodcutting, etc.) from the top 10 users.

Cheers.

**Comment by mrfloris** [comment]
These are now built into mcMMO btw, this addon Is no longer needed as a separate download.

**Comment by Strahilchu** [comment]
> These are now built into mcMMO btw, this addon Is no longer needed as a separate download.

They are? I can't seem to get them to work!

**Comment by SrBedrock** [comment]
@Strahilchu This suggestion has not been implemented here and has not been added to mcMMO either

**Comment by electronicboy** [comment]
I ended up getting severely ill a good while back and before I recovered, nossr had moved the contents of this repo into mcmmo itself, I'd probably suggest filing any feature requests over there
