### ISSUE TITLE
Error placeholders with TAB

### ISSUE THREAD

**Issue by Diablolend** [electronicboy/mcmmo-placeholders#8]
Spam with an error in the log, every time the tab is opened.
Also, %mcmmo_power_level% disappears in the tab.
![javaw_7OByh3d8uP](https://user-images.githubusercontent.com/11898488/125299230-62ced180-e342-11eb-9ef2-67818ea373a7.png)
When i do /tab reload
![javaw_KrdGGKIxmQ](https://user-images.githubusercontent.com/11898488/125299796-e983ae80-e342-11eb-9373-0f84021a67f7.png)

Log with error:
[PlaceholderAPI.errors.log](https://github.com/electronicboy/mcmmo-placeholders/files/6801944/PlaceholderAPI.errors.log)

**Comment by electronicboy** [comment]
This was actually an mcmmo issue from the looks of it
